day7/class_view_demo/class_view_demo/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.views.generic import TemplateView

urlpatterns = [
    path('book/',views.BookListView.as_view(),name='booklist'),
    path('add_book/',views.AddBookView.as_view(),name='add_book'),
    path('book/detail/<book_id>/',views.BookDetailView.as_view(),name='detail'),
    #如果纯静态 可以这么写
    # path('about/',TemplateView.as_view(template_name='about.html'))
    path('about/',views.AboutView.as_view(),name='about'),
    path('article/',include('front.urls'))
]

day7/class_view_demo/front/urls.py
#encoding:utf-8

from django.urls import path
from . import views

app_name = 'front'
urlpatterns = [
    path('add/',views.add_article,name='add_article'),
    path('list/',views.ArticleListView.as_view(),name='list'),
    path('login/',views.login,name='login'),
    path('profile/',views.ProfileView.as_view(),name='profile'),
]

day7/class_view_demo/front/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    create_time = models.DateTimeField(auto_now_add=True)
    class Meta:
        db_table = 'article'

day7/class_view_demo/class_view_demo/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import View,TemplateView


class BookListView(View):
    def get(self,request,*args,**kwargs):
        return render(request,'index.html')
class AddBookView(View):
    #自动判断请求方式 为get 查看添加页面
    def get(self,request,*args,**kwargs):
        return render(request,'add_book.html')
    #自动判断请求方式为post 接收前段用户提交的数据
    def post(self,request,*args,**kwargs):
        book_name = request.POST.get('name')
        book_author = request.POST.get('author')
        print("name:{},author:{}".format(book_name,book_author))
        return HttpResponse("success")

class BookDetailView(View):
    def get(self,request,book_id):
        return HttpResponse('图书的id是:%s' % book_id)

    #如果请求方式不被允许  那么走这里
    def http_method_not_allowed(self, request, *args, **kwargs):
        return HttpResponse("不好意思不支持get以外其它的请求")

    # 不管请求方式是什么 都会走这里
    def dispatch(self, request, *args, **kwargs):
        print("虽然你只支持get请求但是所有请求方法我都会相应一下")
        return super(BookDetailView, self).dispatch(request, *args, **kwargs)


class AboutView(TemplateView):
    template_name = 'about.html'
    def get_context_data(self, **kwargs):
        context = {
            'phone':'13888888888'
        }
        return context

day7/class_view_demo/front/views.py
from django.shortcuts import render,redirect,reverse
from django.http import HttpResponse
from .models import Article
from django.views.generic import View,TemplateView,ListView
from django.utils.decorators import method_decorator
# Create your views here.

def add_article(request):
    articles = []
    for x in range(200):
        article = Article(title='标题：%s' % x,content='内容:%s' % x)
        articles.append(article)
    Article.objects.bulk_create(articles)
    return HttpResponse('成功')

#第一种分页
# class ArticleListView(ListView):
#     model = Article
#     template_name = 'article_list1.html'
#     context_object_name = 'articles'
#     paginate_by = 10
#     ordering = 'create_time'
#     page_kwarg = 'p'
#
#     def get_context_data(self,**kwargs):
#         context = super(ArticleListView, self).get_context_data()
#         paginator = context.get('paginator')
#         page_obj = context.get('page_obj')
#         return context
    #如果你不想要全部数据 只要部分数据 那么 需要重写
    #get_queryset方法
    # def get_queryset(self):
    #     return Article.objects.filter(id__lte=100)

class ArticleListView(ListView):
    model = Article
    template_name = 'article_list.html'
    context_object_name = 'articles'
    paginate_by = 10
    ordering = 'create_time'
    page_kwarg = 'p'

    def get_context_data(self,**kwargs):
        context = super(ArticleListView, self).get_context_data()
        paginator = context.get('paginator')
        page_obj = context.get('page_obj')
        pagination_data = self.get_pagination_data(paginator,page_obj)
        context.update(pagination_data)
        return context

    #知道你左边的页码是多少
    #右边的页码是多少
    #左边是否还有更多页码  #总共10 页  当前第4页 左边没有更多页码了
    #右边是否还有更多页码
    #需要知道当前的页码是多少
    def get_pagination_data(self,paginator,page_obj,arrount_count=2):
        current_page = page_obj.number  #当前页
        number_pages = paginator.num_pages #总共多少页

        left_has_more = False  #标志位 默认左边没有更多
        right_has_more = False  #标志位 默认右边没有更多

        if current_page <= arrount_count + 2:  # 如果当前页码小于等于4
            left_pages = range(1,current_page)  #那么左边页码就显示 1 2 3
        else:
            left_has_more = True   #当前第10页 左边应该显示 89 就是range(8,10)
            left_pages = range(current_page-arrount_count,current_page)

        if current_page >= number_pages-arrount_count-1:
            # 总共40页为例如果当前页码大于等于
            #如果大于等于37页就不能显示省略号了而是显示所有的页码
            right_pages = range(current_page+1,number_pages+1)
            #37 右边应该显示 38 39 40  range(38,41)
        else:
            right_has_more = True   #当前第10页 左边应该显示 89 就是range(8,10)

            right_pages = range(current_page+1,current_page+arrount_count+1) #如果第10页
            #右边应该是 11 12   range(11,13)


        return {
            'left_has_more':left_has_more,
            'right_has_more':right_has_more,
            'left_pages':left_pages,
            'right_pages':right_pages,
            'number_pages':number_pages,
            'current_page':current_page
        }

#web开发中 装饰器是在  response到达浏览器之前调用
#参数是一个方法
#真正执行的是wrapper
def login_required(func):
    def wrapper(request,*args,**kwargs):
        username = request.GET.get('username')
        if username:
            return func(request,*args,**kwargs)
        else:
            return redirect(reverse('front:login'))
    return wrapper


def login(request):
    return HttpResponse('登录页')
#给整个类添加装饰器
#因为每个请求都会走 dispatch 所以name='dispatch '
#dispatch加了装饰器 整个类都加上了
@method_decorator([login_required],name='dispatch')
class ProfileView(View):
    def get(self,request):
        return HttpResponse('个人中心页面')

day7/class_view_demo/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>关于我们</title>
</head>
<body>
    这是关于我们的页面 {{ phone }}
</body>
</html>

day7/class_view_demo/templates/add_book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="" method="post">
    {% csrf_token %}
    <table>
        <tbody>
            <tr>
                <td>图书名字:</td>
                <td><input type="text" name="name" placeholder="请输入图书的名字"></td>
            </tr>
            <tr>
                <td>作者:</td>
                <td><input type="text" name="author" placeholder="请输入作者名称"></td>
            </tr>
            <tr>
                <td></td>
                <td><input type="submit" value="立即添加"></td>
            </tr>
        </tbody>
    </table>
</form>
</body>
</html>

day7/class_view_demo/templates/article_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>文章列表</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
<ul>
    {% for article in articles %}
        <li>{{ article.title }}/{{ article.content }}</li>
    {% endfor %}
    <nav aria-label="Page navigation">
        <ul class="pagination">
            {# 上一页开始#}
            {% if page_obj.has_previous %}
                <li>
                    <a href="{% url 'front:list' %}?p={{ page_obj.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
            {% else %}
                <li class="disabled"><a href="javascript:void(0)"><span aria-hidden="true">&laquo;</span></a>
                </li>
            {% endif %}
            {# 上一页结束#}

             {# 左边的页码#}
              {% if left_has_more %}
                  <li><a href="{% url 'front:list' %}?p=1">1</a></li>
                  <li><a href="javascript:void(0);">...</a></li>
              {% endif %}

             {# 左边的页码 遍历#}
             {% for left_page in left_pages %}
                <li><a href="{% url 'front:list' %}?p={{ left_page }}">{{ left_page }}</a></li>
             {% endfor %}


            {# 当前的页面#}
            <li><a href="{% url 'front:list' %}?p={{ current_page }}">{{ current_page }}</a></li>
            {# 右边的页码#}
            {% for right_page in right_pages %}
                <li><a href="{% url 'front:list' %}?p={{ right_page }}">{{ right_page }}</a></li>
             {% endfor %}

             {% if right_has_more %}
                  <li><a href="javascript:void(0);">...</a></li>
                  <li><a href="{% url 'front:list' %}?p={{ number_pages }}">{{ number_pages }}</a></li>

              {% endif %}


            {#下一页开始#}
            {% if page_obj.has_next %}
                <li>
                    <a href="{% url 'front:list' %}?p={{ page_obj.next_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            {% else %}
                <li class="disabled">
                    <a href="javascript:void(0)"><span aria-hidden="true">&raquo;</span></a>
                </li>
            {% endif %}
            {#下一页结束#}
        </ul>
    </nav>
</ul>
</body>
</html>

day7/class_view_demo/templates/article_list1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>文章列表</title>
    <!-- 最新版本的 Bootstrap 核心 CSS 文件 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
    <ul>
    {% for article in articles %}
        <li>{{ article.title }}/{{ article.content }}</li>
    {% endfor %}
    <nav aria-label="Page navigation">
  <ul class="pagination">
    {# 上一页开始#}
      {% if page_obj.has_previous %}
        <li>
            <a href="{% url 'front:list' %}?p={{ page_obj.previous_page_number }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
      {% else %}
          <li class="disabled">
              <a href="javascript:void(0)"><span aria-hidden="true">&laquo;</span></a>
          </li>
      {% endif %}
    {# 上一页结束#}
    {#中间页码#}
    {% for page in paginator.page_range %}
        {% if page_obj.number == page %}
             <li class="active"><a href="javascript:void(0)">{{ page }}</a></li>
        {% else %}
            <li ><a href="{% url 'front:list' %}?p={{ page }}">{{ page }}</a></li>
        {% endif %}

    {% endfor %}

    {#中间页码#}
    {#下一页开始#}
   {% if page_obj.has_next %}
        <li>
            <a href="{% url 'front:list' %}?p={{ page_obj.next_page_number }}" aria-label="Previous">
            <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
      {% else %}
          <li class="disabled">
              <a href="javascript:void(0)"><span aria-hidden="true">&raquo;</span></a>
          </li>
      {% endif %}
    {#下一页结束#}
  </ul>
</nav>
    </ul>

</body>
</html>

day7/class_view_demo/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
</head>
<body>
    图书列表
</body>
</html>